# Generated by Django 5.2.5 on 2025-09-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_birth_date_account_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='birth_date',
            new_name='birthdate',
        ),
    ]
